### ISSUE TITLE
*beast2RLC: Fatal exception based on incomplete taxon representation

### ISSUE THREAD

**Issue by rbouckaert** [genomescale/starbeast2#16]
This was submitted as a BEAST 2 issue [#715](https://github.com/CompEvol/beast2/issues/715), but I think this is a SartBEAST2 issue.

Hi there,

I'm trying to run *beast2RLC with 60 odd gene trees and up to 24 taxa. Looks like the problem is that not all taxa are represented in every gene alignment.

Test dataset with *beast2 RLC template worked fine previously, at that point taxa were represented in all gene alignments. Ran on Linux based cluster as well as Ubuntu OS laptop - this error is coming up for both systems now.

Is there a way to make this run without screening which taxa are missing in each gene alignment and then adding gaps? Thanks!

StarBEAST2: using fullInit to initialize all trees.
Fatal exception: Gene tree Tree.t:EPrGT00050000005290 has no lineages for species taxon ALEXANDRIUM-CATENELLA
java.lang.RuntimeException: Gene tree Tree.t:EPrGT00050000005290 has no lineages for species taxon ALEXANDRIUM-CATENELLA
at starbeast2.StarBeastInitializer.fullInit(StarBeastInitializer.java:246)
at starbeast2.StarBeastInitializer.initStateNodes(StarBeastInitializer.java:101)
at beast.core.MCMC.run(Unknown Source)
at beast.app.BeastMCMC.run(Unknown Source)
at beast.app.beastapp.BeastMain.(Unknown Source)
at beast.app.beastapp.BeastMain.main(Unknown Source)
at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: Gene tree Tree.t:EPrGT00050000005290 has no lineages for species taxon ALEXANDRIUM-CATENELLA
java.lang.RuntimeException: An error was encounted. Terminating BEAST
at beast.app.util.ErrorLogHandler.publish(Unknown Source)
at java.util.logging.Logger.log(Logger.java:738)
at java.util.logging.Logger.doLog(Logger.java:765)
at java.util.logging.Logger.log(Logger.java:788)
at java.util.logging.Logger.severe(Logger.java:1464)
at beast.app.beastapp.BeastMain.(Unknown Source)
at beast.app.beastapp.BeastMain.main(Unknown Source)
at beast.app.beastapp.BeastLauncher.main(Unknown Source)

**Comment by genomescale** [comment]
This is fixed in version 0.14, thanks for transferring the issue over to the right repo @rbouckaert

**Comment by mariaemilyd** [comment]
Hi there, I'm getting the same error message that not all taxa are represented in every gene alignment.  I'm using StarBEAST v 0.15.5 and BEAST v2.6.0:

Fatal exception: Gene tree Tree.t:O_rosmarus_Lindqvist_2016_NADH_all_aligned_seq_27_11_2018 has no lineages for species taxon Eastern_Laptev 
java.lang.RuntimeException: Gene tree Tree.t:O_rosmarus_Lindqvist_2016_NADH_all_aligned_seq_27_11_2018 has no lineages for species taxon Eastern_Laptev 
	at beast.evolution.speciation.StarBeastStartState.fullInit(Unknown Source)
	at beast.evolution.speciation.StarBeastStartState.initStateNodes(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at beast.app.beastapp.BeastLauncher.run(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Fatal exception: Gene tree Tree.t:O_rosmarus_Lindqvist_2016_NADH_all_aligned_seq_27_11_2018 has no lineages for species taxon Eastern_Laptev 

BEAST has terminated with an error. Please select QUIT from the menu.


Thanks!

**Comment by genomescale** [comment]
Hi Maria, this is the old *BEAST implementation, to be able to run an analysis with missing data you should use one of the StarBEAST2 templates (see the StarBEAST2 tutorial for details)

Regards,

Huw
